name: Phishio CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          # Removido o 'cd backend'
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest httpx # <-- Adicionado o httpx para a API

      - name: Run Tests
        run: |
          # Removido o 'cd backend' e adicionado o PYTHONPATH
          PYTHONPATH=. pytest tests/ -v

  package-extension:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip Chrome Extension
        run: |
          zip -r phishio_extension.zip extension/